### ISSUE TITLE
Result from interactive calculator is missing mandatory prefix for CVSSv3

### ISSUE THREAD

**Issue by vkrizan** [skontar/cvss#12]
Cannot use interactive calculator for CVSSv3. `ask_interactively` returns vector without mandatory "CVSS:3.0" prefix. That results in CVSS3MalformedError (unable to feed the result to `CVSS3` constructor):

```
cvss.exceptions.CVSS3MalformedError: Malformed CVSS3 vector "AV:N/AC:L/PR:H/UI:R/S:C/C:L/I:L/A:H" is missing mandatory prefix
```

**Comment by skontar** [comment]
Fixed in 8c338ab3f6cf1422357c2bdd9b266c7caae7171b.
