### ISSUE TITLE
Support for CVSS 3.1

### ISSUE THREAD

**Issue by bac** [skontar/cvss#21]
Hi,

Will you be updating to support 3.1? The changes to scoring look minimal.

https://www.first.org/cvss/user-guide#CVSS-Version-3-1-Release

**Comment by skontar** [comment]
Yes, that is planned. I am aware of rounding changes but did not look into changed equations yet. It may take some time.

**Comment by Thomas-Alex** [comment]
Hopefully this should help:
#22

**Comment by skontar** [comment]
Hi @bac , would you mind checking out https://github.com/skontar/cvss/pull/23 ? Thanks!

**Comment by skontar** [comment]
Fixed with #23
