### ISSUE TITLE
Make a release on PyPI?

### ISSUE THREAD

**Issue by pombredanne** [skontar/cvss#33]
It would be awesome if you mind to cut a release with the latest commit.
Thanks!

**Comment by pombredanne** [comment]
FWIW, this is for integration in https://github.com/nexb/vulnerablecode

**Comment by skontar** [comment]
Release done. Please check it out and verify it works as intended. I no longer use the library so double-checking would be appreciated. Thanks!

**Comment by pombredanne** [comment]
@skontar Thanks!
