### ISSUE TITLE
No errors when an alien prefix is present in vector for CVSS3

### ISSUE THREAD

**Issue by vkrizan** [skontar/cvss#4]
When adding a prefix to CVSS3 vector for constructor, no error is produced. Prefix is silently dropped.

```
>>> CVSS3('CVSS:3.0/AV:N/AC:H/PR:L/UI:N/S:C/C:L/I:L/A:N')
<cvss.cvss3.CVSS3 object at 0x...>
```

Please also check same issue for CVSS2 and for alien prefixes.

Thanks.

**Comment by skontar** [comment]
`CVSS:3.0/` prefix is part of the specification, so it needs to be accepted. Other prefixes are not accepted.
