### ISSUE TITLE
License request

### ISSUE THREAD

**Issue by pombredanne** [skontar/cvss#6]
Hi: 
Thank you for this code! 
Would you consider an alternative license such ass LGPL or else such this library can be used in other non-GPL FLOSS tool such as my https://github.com/nexB/scancode-toolkit which is Apache-licensed?
Thank you for you consideration. Feel free to ignore and close this if you feel strongly about the GPL.

**Comment by skontar** [comment]
Hi. LGPL should not be a problem. I am not an expert in licenses, so I hope to look into it during next week for more details. Thanks.

**Comment by pombredanne** [comment]
@skontar Thanks you for the quick plrey. LGPL would be perfect if that can be done.

**Comment by skontar** [comment]
@pombredanne The version 1.4 of the library is now licensed under LGPL3+. Thanks for your interest.

**Comment by pombredanne** [comment]
@skontar Thanks ++
